# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: observation.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='observation.proto',
  package='SourceNode',
  syntax='proto2',
  serialized_pb=_b('\n\x11observation.proto\x12\nSourceNode\"9\n\x0bObservation\x12\t\n\x01r\x18\x01 \x02(\x02\x12\t\n\x01\x64\x18\x02 \x02(\x05\x12\t\n\x01\x66\x18\x03 \x02(\x05\x12\t\n\x01t\x18\x04 \x02(\x03')
)




_OBSERVATION = _descriptor.Descriptor(
  name='Observation',
  full_name='SourceNode.Observation',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='r', full_name='SourceNode.Observation.r', index=0,
      number=1, type=2, cpp_type=6, label=2,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='d', full_name='SourceNode.Observation.d', index=1,
      number=2, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='f', full_name='SourceNode.Observation.f', index=2,
      number=3, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='t', full_name='SourceNode.Observation.t', index=3,
      number=4, type=3, cpp_type=2, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=33,
  serialized_end=90,
)

DESCRIPTOR.message_types_by_name['Observation'] = _OBSERVATION
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Observation = _reflection.GeneratedProtocolMessageType('Observation', (_message.Message,), dict(
  DESCRIPTOR = _OBSERVATION,
  __module__ = 'observation_pb2'
  # @@protoc_insertion_point(class_scope:SourceNode.Observation)
  ))
_sym_db.RegisterMessage(Observation)


# @@protoc_insertion_point(module_scope)
